name: DanielN
favicon: null
layout_spectrum: 0.31397566734813154
typography_spectrum: 0.8803494079038501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6269672203343362
  lightness: 0.20703900046646595
  saturation: 0.9459282564930618
  rhythmicContrast: 0.04596487991511822
purpose: []
